services:
  - type: web
    plan: free
    name: RenameBot-Premium
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/TN69Links-Saravana/RenameBot-Premium.git      
    branch: webx
    envVars:
      - key: ADMIN 
        sync: false
      - key: DB_URL 
        sync: false
      - key: DB_NAME
        sync: false
      - key: LOG_CHANNEL
        sync: false
    autoDeploy: false
